### ISSUE TITLE
Turning off Secure boot

### ISSUE THREAD

**Issue by Ddevendra** [potato1992/Iphone_usb_tethering_fix#3]
Build is all good doesn't need any extra permissions, but installing requires secure boot to be turned off.
After installation secure boot must be turned off or else OS won't detect the USB Ethernet profile

OS : GNU/Linux ubuntu 18.04.5 LTS
kernel : 5.4.0-65-generic

**Comment by potato1992** [comment]
> Build is all good doesn't need any extra permissions, but installing requires secure boot to be turned off.
> After installation secure boot must be turned off or else OS won't detect the USB Ethernet profile
> 
> OS : GNU/Linux ubuntu 18.04.5 LTS
> kernel : 5.4.0-65-generic

I have update the repository to help users with the security boot. As I do not use security boot myself, please report to me if it works.

**Comment by Ddevendra** [comment]
Yes it Worked.

but there is little problem with this command 

```openssl req -config ./openssl.cnf -new -x509 -newkey rsa:2048 -nodes -days 36500 -outform DER -keyout "my_mok.priv" -out "my_mok.der"```

the ```./openssl.cnf``` should be PATH to openssl.cnf file (e.g /etc/ssl/openssl.cnf)

**Comment by potato1992** [comment]
> Yes it Worked.
> 
> but there is little problem with this command
> 
> `openssl req -config ./openssl.cnf -new -x509 -newkey rsa:2048 -nodes -days 36500 -outform DER -keyout "my_mok.priv" -out "my_mok.der"`
> 
> the `./openssl.cnf` should be PATH to openssl.cnf file (e.g /etc/ssl/openssl.cnf)

Since I have no idea if everyone has the file  /etc/ssl/openssl.cnf, thus I have attached one in the repository root directory, thus people should also be able to use the attached one to make it work....

**Comment by potato1992** [comment]
I am closing this issue since it seems solved.
