### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by SarahH12099** [potato1992/Iphone_usb_tethering_fix#4]
Hello, so I ran your script then rebooted once it is complete and it still didn't work for me via Tethering using TetherMe (A tether tool for ios jb).

Details:
Operating System: Linux
Distro: Linux Mint 20.1 Cinnamon
Kernel: 5.4.0-70-generic

Does it not work after a reboot?

**Comment by potato1992** [comment]
Hello, it should work after a reboot.
I do not know how does the TetherMe work or whether it relies on the ipheth module. Can you test with [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice) to test whether the tethering is working properly?
If your os is based on Debian, just install **libimobiledevice** with:
```
sudo apt-get install ipheth-utils libimobiledevice-dev libimobiledevice-utils
```
IOS does not require any third-party software for usb-tethering to work properly. Just open the hotspot in setttings and plug in the usb cable.

update:
I found that on one of my device I have to install usbmuxd:

```
sudo apt-get install usbmuxd
```

**Comment by potato1992** [comment]
I am closing this issue as no response has been received for 2 years.
