### ISSUE TITLE
Does updating my kernel undo the changes made by this?

### ISSUE THREAD

**Issue by SarahH12099** [potato1992/Iphone_usb_tethering_fix#5]
Hello, I was wondering does updating my kernel overwrite the changes done by this please?

**Comment by potato1992** [comment]
> Hello, I was wondering does updating my kernel overwrite the changes done by this please?

I have not tested for it thus I have no idea whether the kernel upgrade will overwrite the changes, but I am assuming that it does.

**Comment by potato1992** [comment]
I am closing this issue as no response has been received for 2 years.
